### ISSUE TITLE
"*" as folder name is causing issues on windows

### ISSUE THREAD

**Issue by isaactetteh** [databricks/LearningSparkV2#52]
the path __databricks-datasets/learning-spark-v2/flights/summary-data/avro/*/__ is causing issues when you clone the repo.

**Comment by dmatrix** [comment]
Do you mean you can't clone on a windows machine or are you when you execute the code with this path windows is causing issues?

cc @brookewenig @dennyglee 
Can you elaborate?

**Comment by isaactetteh** [comment]
@dmatrix , Yes, I can't clone on windows. I get the following message from git

```
Cloning into 'LearningSparkV2'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 1647 (delta 22), reused 35 (delta 9), pack-reused 1577
Receiving objects: 100% (1647/1647), 75.56 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (509/509), done.
error: invalid path 'databricks-datasets/learning-spark-v2/flights/summary-data/avro/*/_SUCCESS'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```
Even when I download the repo as zip and unzip it, I lose all the files under databricks-datasets/learning-spark-v2/flights/summary-data/avro/ and other files due to the length of file names.

**Comment by dmatrix** [comment]
@isaactetteh, 
Do you have access to a UNIX based laptop? This seems to be unique and specific to windows.

**Comment by isaactetteh** [comment]
Yeah I used linux machine and it worked fine.
