### ISSUE TITLE
Donation to charity for erratum?

### ISSUE THREAD

**Issue by raybellwaves** [databricks/LearningSparkV2#55]
I wonder if I can entice you follow suit with @rasbt and make donations to a charity for users reporting erratum? It's a fun (@rasbt even made it competitive) way to crowd source errors in the book.

See https://github.com/rasbt/python-machine-learning-book/blob/master/docs/errata.md

Could even look to something on the README so users don't report the same error

**Comment by dmatrix** [comment]
@raybellwaves Thanks for the kind suggestion. This is a great idea for GitHub and free books. Perhaps for future projects, we may consider having a pre-release book for crowdsourcing errors in the book, working with our publishers and editors. 

Thanks for the kind suggestions.
