### ISSUE TITLE
Error p138. Chapter 5 - Higher-Order Functions in DataFrames and Spark SQL

### ISSUE THREAD

**Issue by raybellwaves** [databricks/LearningSparkV2#56]
Under Option 2: User-Defined Function the code is copied from the example above (Option 1: Explode and Collect). I believe it's missing a UDF that uses `map`

![IMG_5158](https://user-images.githubusercontent.com/17162724/92061165-9379ce00-ed63-11ea-960a-dbc98824f8f8.jpg)

**Comment by dennyglee** [comment]
Thanks, @raybellwaves - this has been submitted and will be addressed via the [Learning Spark 2nd Edition Errata](https://www.oreilly.com/catalog/errata.csp?isbn=0636920240303).  

Quick note, the code in question should actually be:
```
// In Scala
def addOne(values: Seq[Int]): Seq[Int] = {
    values.map(value => value + 1)
}
val plusOneInt = spark.udf.register("plusOneInt", addOne(_: Seq[Int]): Seq[Int])
```

Thanks again!
