### ISSUE TITLE
Fig 10-4 use of shapes?

### ISSUE THREAD

**Issue by raybellwaves** [databricks/LearningSparkV2#57]
The cluster example in Fig 10-4 was a bit difficult to follow in black and white print. Could use different shapes to plot the clusters instead of colors?

![IMG_5159](https://user-images.githubusercontent.com/17162724/92061385-23b81300-ed64-11ea-97f7-ed275da1ef69.jpg)

**Comment by brookewenig** [comment]
That is an excellent point! In the digital copy (which you can get for free from here: https://databricks.com/p/ebook/learning-spark-from-oreilly) has the book in color. I'll make this note to O'Reilly for future print releases.
