### ISSUE TITLE
Table 10-2 error?

### ISSUE THREAD

**Issue by raybellwaves** [databricks/LearningSparkV2#58]
Am I right in thinking that 'Deprecated' and 'N/A' should switch places in Table 10-2?

![IMG_5161](https://user-images.githubusercontent.com/17162724/92061560-9aeda700-ed64-11ea-97b2-0bb97e89fda4.jpg)

**Comment by brookewenig** [comment]
No - it is correct where it is. You can see in the [Spark 2.3 docs](https://spark.apache.org/docs/2.3.0/api/python/pyspark.ml.html#pyspark.ml.feature.OneHotEncoder) that the OneHotEncoder is deprecated, and there is no OneHotEncoderEstimator is Spark 3.0.
