### ISSUE TITLE
Error p 309. Chapter 10 - Decision trees code example

### ISSUE THREAD

**Issue by raybellwaves** [databricks/LearningSparkV2#59]
In the following code example I couldn't see where `indexOutputCols` is defined

![IMG_5162](https://user-images.githubusercontent.com/17162724/92062950-ea81a200-ed67-11ea-9731-0100b57276b8.jpg)

**Comment by brookewenig** [comment]
Excellent point! We defined indexOutputCols earlier when we built a model using linear regression, and omitted it here, along with the StringIndexer, to reduce repetitive code. You can see it's defined on pg 299
