### ISSUE TITLE
Chapter 5 Spark SQL Shell + accessing person table through spark session

### ISSUE THREAD

**Issue by slum44** [databricks/LearningSparkV2#61]
Hi, I'm new to Spark and really appreciate and like this book so far.

I'm currently doing Chapter 5 and I've created the "person" table through the spark-sql shell via command line

I've killed my spark-sql shell and I can see that the "person" table is persisted across spark-sql shell sessions since when I run a new spark-sql shell the person table is still there

I restarted my spark master as well and spark-sql shell session and the person table still exists

One thing I think this chapter (and book|) is lacking - it doesn't mention how I can interact and insert more rows into this table outside of the spark-sql shell in for example a scala spark submit process

I tried the following code below but the "person" table is not found

Would appreciate if someone can advise - I don't see the link / connection b/w the person table in hive and how I can use from other spark sessions

```

  def main(args: Array[String]) {
    val start = Instant.now

    Logger.getLogger("org").setLevel(Level.INFO)

    val warehouseLocation = new File("spark-warehouse").getAbsolutePath

    // Create a SparkSession without specifying master
    val spark = SparkSession
      .builder
      .master("spark://localhost:7077")
      .appName("PeopleQuery")
      .config("spark.sql.warehouse.dir", warehouseLocation)
      .enableHiveSupport()
      .getOrCreate()

    val sqlDF = spark.sql("select * from people;")
    println(sqlDF.show())
  }

```

**Comment by dennyglee** [comment]
Hi @slum44 - the purpose of this github is to provide issues around the book code-base.  For questions like these, it may make more sense to ping StackOverflow.   Saying this, allow me to try to respond to some of your questions:

```
One thing I think this chapter (and book|) is lacking - it doesn't mention how I can interact and insert more rows into this table outside of the spark-sql shell in for example a scala spark submit process
```
You will want to review other sections of the book for this information as the goal of this chapter was to talk about *Interacting with External Data Sources*.   To insert other rows using Spark SQL, you can use `insert into person select co1... from other_table` syntax.  For examples on spark-submit process, please refer to the earlier chapters that show how you can use spark-submit.

In terms of using the person Table in Hive, I believe you're referring to the Hive metastore which is a catalog that contains the metadata for the said table.  By having  this catalog, you can have multiple processes (Spark or other compatible systems) know how to interact with the table which is itself made up of files.
