### ISSUE TITLE
Cloning the repository fails with an error, and all files are marked as DELETED.

### ISSUE THREAD

**Issue by abhaysibal** [databricks/LearningSparkV2#63]
Doing a git clone for this repository fails with this error:

Cloning into 'LearningSparkV2'...
remote: Enumerating objects: 126, done.
remote: Counting objects: 100% (126/126), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 1703 (delta 35), reused 76 (delta 19), pack-reused 1577
Receiving objects: 100% (1703/1703), 76.00 MiB | 16.12 MiB/s, done.
Resolving deltas: 100% (522/522), done.
**error: invalid path 'databricks-datasets/learning-spark-v2/flights/summary-data/avro/*/_SUCCESS'**
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Operating System: Windows 10
Git version : git version 2.26.2.windows.1

**Comment by ali-khawaja** [comment]
i am getting the same error, you can do the git restore command as mentioned in the message and it will give you everything that was downloaded:

git restore --source=HEAD :/

**Comment by dmatrix** [comment]
This is related to #52, which has been closed.

**Comment by ali-khawaja** [comment]
yes, you cannot have * as a directory name in windows.  is it possible to change that?

**Comment by abhaysibal** [comment]
I agree with @ali-khawaja . This blocks stuff for Windows users, even though Spark runs for both Win and Linux.

**Comment by akanz1** [comment]
If you don't mind that one directory you can either remove it or clone from here
