### ISSUE TITLE
Chapter 5 - Joins - Incorrect python code

### ISSUE THREAD

**Issue by skodman** [databricks/LearningSparkV2#67]
On page 148, python code for explaining joins is incorrect. It reads:

```python
# In Python
# Join departure delays data (foo) with airport info
foo.join(
  airports,
  airports.IATA == foo.origin
).select("City", "State", "date", "delay", "distance", "destination").show()

```
However, the airports ```airports``` dataframe does not exist. It should be changed to ```airportsna```, as follows:
```python
# In Python
# Join departure delays data (foo) with airport info
foo.join(
  airportsna,
  airportsna.IATA == foo.origin
).select("City", "State", "date", "delay", "distance", "destination").show()

```
Then the code works.

**Comment by brookewenig** [comment]
Thanks for catching this @skodman! The scala code correctly uses `airports`, but the Python code uses `airportsna`. We'll fix this in the next pdf release. cc @dennyglee. 

If there are no further issues, can we close this?

**Comment by skodman** [comment]
Yes this can be closed. I am going through the book and will raise any other issues separately.

cheers
skodman
