### ISSUE TITLE
IoT Devices Notebook (Scala) throws an `AnalysisException` on reading from Json and parsing as `DeviceIoTData` case class  

### ISSUE THREAD

**Issue by balath** [databricks/LearningSparkV2#69]
Firstly, I was trying the Dataset examples on my own but without being able to obtain a Dataset[DeviceIoTData] from the Json data. Then, I tried with the notebook imported from this repo and it kept failing again:
![imagen](https://user-images.githubusercontent.com/55799381/133213244-09901e8d-5dab-4759-bf8d-490ce776cf6a.png)
Where is my mistake? Thanks! ^^

**Comment by brookewenig** [comment]
Hey @balath! All the datasets located in databricks-datasets are accessible in Databricks Community Edition. Could you use this path instead `/databricks-datasets/learning-spark-v2/iot-devices/iot_devices.json"`?

**Comment by balath** [comment]
Hi @brookewenig!! That path works! My downloaded json seems to have been corrupted while downloading or anything... From now on, I'll use that path for data. Lots of thanks!!! 💯 🤗
