### ISSUE TITLE
cloning the repo fails

### ISSUE THREAD

**Issue by KVSSetty** [databricks/LearningSparkV2#70]
Hello, I am learning Spark through your book, but when tried to clone the repo , I am getting this error , any help?

Cloning into 'D:\LearningSparkV2'...
remote: Enumerating objects: 1712, done.        
remote: Counting objects: 100% (135/135), done.        
remote: Compressing objects: 100% (92/92), done.        
remote: Total 1712 (delta 38), reused 85 (delta 23), pack-reused 1577        
Receiving objects: 100% (1712/1712), 76.76 MiB | 2.72 MiB/s, done.
Resolving deltas: 100% (525/525), done.
error: invalid path 'databricks-datasets/learning-spark-v2/flights/summary-data/avro/*/_SUCCESS'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by brookewenig** [comment]
Do you have a Linux machine you can use? This seems to be unique and specific to windows (see https://github.com/databricks/LearningSparkV2/issues/63)

**Comment by KVSSetty** [comment]
sorry I don't have Linux. but sometimes I use wsl2, but I am very poor at Linux
