### ISSUE TITLE
missing source file

### ISSUE THREAD

**Issue by tiagobalabuch** [databricks/LearningSparkV2#71]
I am trying to follow chapter 6 - Scala notebook: 6-2 Dataset API and I couldn't find this file path (mnt/training/dataframes/people-with-header-10m.txt) in the github to use in my environment.

Other datasets are available in databricks-datasets/learning-spark-v2 however this one isn't there.

**Comment by brookewenig** [comment]
Apologies for this! The dataset is too large to put in git, but the proper path should be: databricks-datasets/learning-spark-v2/people/people-with-header-10m.txt (that is accessible from any Databricks workspace, including Community Edition).

Could you check and see if that path works for you? I'll update the main DBC so others don't hit this issue.

**Comment by tiagobalabuch** [comment]
Hi @brookewenig, after changing the path, it worked! Thanks

**Comment by brookewenig** [comment]
Thanks for confirming!
