### ISSUE TITLE
Error in Chapter 3: "ResponseDelayedinMins" => "ResponseDelayedMins"

### ISSUE THREAD

**Issue by tomharrisonjr** [databricks/LearningSparkV2#73]
Page 96 (Location 1999 in Kindle)

**Comment by brookewenig** [comment]
Thanks for flagging @tomharrisonjr! 

Please let me know if I'm looking at the right spot. I only see ResponseDelayedinMins occurring in pages 63-68. Is this comment related to improved naming convention?

**Comment by tomharrisonjr** [comment]
looks like I missed the whole part about changing column names. Sorry, not an issue. 

Closing.
